### ISSUE TITLE
Receiving 401 after authentication

### ISSUE THREAD

**Issue by lucasshd** [SufyanDahalan/VSWorkbench#1]
I entered my gitlab instance and my generated access-token with api scope, but every time I try to load my Groups or everything I get an 401. The access-token is valid, I checked it.

**Comment by SufyanDahalan** [comment]
Hi @lucasshd. Thanks for opening an issue. 
I updated the extension to give clearer info about the GitLab instance URL. 
The URL has to fit the following syntax:
`https://gitlab.com`
